language: php
php:
  - hhvm
before_script: composer install
before_install:
  - cat /etc/hhvm/php.ini
  - echo hhvm.enable_zend_compat=true | sudo tee -a /etc/hhvm/php.ini
script: phpunit
services:
  - redis-server
  - mongodb