language: php
php:
  - hhvm
before_script: composer install
before_install:
  - cat /etc/hhvm/php.ini
  - echo hhvm.enable_zend_compat=true | sudo tee -a /etc/hhvm/php.ini
install:
  - sudo apt-get install cmake
  - sudo mkdir /etc/hhvm/extensions/
  - echo hhvm.dynamic_extension_path = /etc/hhvm/extensions  | sudo tee -a /etc/hhvm/php.ini
  - echo hhvm.dynamic_extensions[mongo] = mongo.so  | sudo tee -a /etc/hhvm/php.ini
  - echo hhvm.dynamic_extensions[msgpack] = msgpack.so  | sudo tee -a /etc/hhvm/php.ini
  - git clone git://github.com/reeze/msgpack-hhvm.git 
  - cd msgpack-hhvm && hphpize && cmake . && make
  - sudo cp msgpack.so /etc/hhvm/extensions/
  - git clone git://github.com/mongofill/mongofill-hhvm.git
  - cd mongofill-hhvm &&  ./build.sh
  - sudo cp mongo.so /etc/hhvm/extensions/
script: phpunit
services:
  - redis-server
  - mongodb